### ISSUE TITLE
bug: `jsonschema.Reflector.ReflectFromType` misses methods defined on pointer receiver

### ISSUE THREAD

**Issue by candiduslynx** [invopop/jsonschema#102]
If we have the following type

```go
type S struct {}

func (*S) JSONSchemaExtend(sc *jsonschema.Schema) {}
```

then the reflection will miss the fact that the type implements the method.

There's a workaround to defint the func having value receiver, but the pointer receiver should also work.

**Comment by samlown** [comment]
I don't agree with the assumption there. JSON Schema always operates on object instances as opposed to pointers so the code could become messy attempting to solve this. I've updated the README to try and clarify this at least.
