### ISSUE TITLE
Custom Slice type doesn't support default values in struct tags

### ISSUE THREAD

**Issue by AmadeusK525** [invopop/jsonschema#127]
Hey, I've been trying to generate a schema for a custom slice type which is a field in a struct, but the `default` values aren't computed

```golang
type MyString string
type MyStrings []MyString

type MyObject struct {
        strs MyStrings `json:"my_strings" jsonschema:"description=This is my description,default=some,default=other"`
}
```

The `MyStrings` definition is correct, with a schema of type `array`, and items of type `string`. In the struct schema, there is the property `my_strings`, which points to the `MyStrings` ref and with the CORRECT description. But there are no default values. I evaluated this by marshaling the resulting schema.

As soon as I use `[]string` instead of `MyStrings`, the default values show up

I may try to fix it on my spare time, but does anyone have any clue on what might be going on?

**Comment by AmadeusK525** [comment]
This was a mistake on my side lol

**Comment by AmadeusK525** [comment]
Re-purposed the issue because there *is* a bug! But not the one I initially suspected

**Comment by samlown** [comment]
I'm not sure about this one... wouldn't the default examples need to be arrays to match the type? Go tags are very limited for more complex scenarios, you'll probably find it easier to break out into one of the `JSONSchema` or `JSONSchemaExtend` methods to customise the output.
