### ISSUE TITLE
Generating JSON Schema `enum` from go `const` for a custom `type` alias (`string` or similar)

### ISSUE THREAD

**Issue by JannikGM** [invopop/jsonschema#128]
I'm aware of the ability to generate an `enum` (like https://json-schema.org/understanding-json-schema/reference/enum) with the `jsonschema:"enum=red,enum=green,enum=blue"` tag; however, I'd like to automatically extract it from the const values provided for a type:

```golang
type Color string

const (
	Red   Color = "red"
	Green Color = "green"
	Blue  Color = "blue"
)

type DemoStruct struct {
	Color Color `json:"color"`
}

// [...]

demo := jsonschema.Reflect(&DemoStruct{})
```

Currently gives this:

```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "[...]",
  "$ref": "#/$defs/DemoStruct",
  "$defs": {
    "DemoStruct": {
      "properties": { "color": { "type": "string" } },
      "additionalProperties": false,
      "type": "object",
      "required": ["color"]
    }
  }
}
```

However, I'd like this to be something more like this:

```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "[...]",
  "$ref": "#/$defs/DemoStruct",
  "$defs": {
    "Color": {
      "enum": [
        "red",
        "green",
        "blue"
      ]
    },
    "DemoStruct": {
      "properties": {
        "color": {
          "$ref": "#/$defs/Color"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "color"
      ]
    }
  }
}
```

Is this already possible? How?
How could this be implemented or what kind of code pattern would you recommend to work around this?

Manually adding each enum value is not feasible.
We try to minimize code/constant duplication as we have a relatively large number of types which are already written this way.

**Comment by samlown** [comment]
Whenever I'm dealing with cases like this I use the `JSONSchemaExtend` method to add the constants manually. For example, not quite the same, but similar: https://github.com/invopop/gobl/blob/main/pay/terms.go#L146.

You could also try adding the `JSONSchema` interface method to `Color` and generate your list. Example: https://github.com/invopop/gobl/blob/main/cbc/key.go#L119

Let me know if these don't work and I'll re-open.
