### ISSUE TITLE
can you generate JSONschema from an enum?

### ISSUE THREAD

**Issue by straz** [invopop/jsonschema#145]
My enum looks like this:

```go
type ImageType string

const (
    JPG    ImageType = "jpg"
    GIF    ImageType = "gif"
    TIFF   ImageType = "tiff"
    PNG    ImageType = "png"
)
```

but when I run `jsonschema.ReflectFromType` all I get is this
```json
{"$schema": "https://json-schema.org/draft/2020-12/schema", "type": "string"}
```

It doesn't even contain the name of the enum as the value of `$ref`. 
I assume that the output I need is something like this, am I right? If so, how do I generate this?
```json
{
  "$schema": "http://json-schema.org/draft/2020-12/schema",
  "$ref": "#/$defs/ImageType",
  "$defs": {
    "ImageType": {
      "properties": {
        "type": "string",
        "enum": ["jpg", "gif", "tiff", "png"]
      }
    }
  }
}

```

**Comment by straz** [comment]
Additionally, I reference this from a `struct` like this:

```go
type Avatar struct {
    Name    string   `json:"name"`
    Type    ImageType   `json:"type"`
}
```

but the output jsonschema ignores the type, and just uses `string`. How do I get it to restrict this to the enum values instead?

```json
{
  "Avatar": {
    "properties": {
      "name": {
        "type": "string"
      },
      "claimType": {
        "type": "string"
      }
    }
  }
}
```

**Comment by samlown** [comment]
For situations like this I almost always use the `JSONSchema() *Schema` or `JSONSchemaExtend(schema *jsonschema.Schema)` [methods](https://github.com/invopop/jsonschema?tab=readme-ov-file#custom-type-definitions) to define custom output.
