### ISSUE TITLE
Setting ExpandedStruct to true returns invalid JSON Schema

### ISSUE THREAD

**Issue by mitar** [invopop/jsonschema#148]
I have a struct like this:

```go
type OutputStruct struct {
	Key      string         `json:"key"`
	Value    int            `json:"value"`
	Children []OutputStruct `json:"children,omitempty"`
}
```

When generating a JSON Schema like:

```go
	r := &jsonschemaGen.Reflector{
		ExpandedStruct: true,
	}
	schema := r.Reflect(&OutputStruct{})
```

I get JSON Schema like:

```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "output-struct",
  "properties": {
    "key": {
      "type": "string"
    },
    "value": {
      "type": "integer"
    },
    "children": {
      "items": {
        "$ref": "#/$defs/OutputStruct"
      },
      "type": "array"
    }
  },
  "additionalProperties": false,
  "type": "object",
  "required": [
    "key",
    "value"
  ],
  "title": "OutputStruct"
}
```

The issue is that `children`'s `items` have:

```
"$ref": "#/$defs/OutputStruct"
```

But `$defs` are gone.

**Comment by samlown** [comment]
Okay, took me a while to figure this one out 😆  you didn't mention you're dealing with a circular dependency! What you're proposing here is not possible at the moment as the generator does not know how to reference itself when your dealing with `ExpandedStruct: true`. Setting that to false should resolve the problem, with the trade-off that all the objects will be inside the `$defs`.

**Comment by mitar** [comment]
But you could you simply provide a way for `$defs` to not be removed while expanded at the same time? That would work, no?
