### ISSUE TITLE
Typo in README example

### ISSUE THREAD

**Issue by Lautarotetamusa** [invopop/jsonschema#152]
The struct in the example its called 'TestUser' 

![TestUser](https://github.com/user-attachments/assets/1da5fc4a-cbda-4dc4-ab82-d3bccec93b5c)
https://github.com/invopop/jsonschema/blob/a4467074499db5797e8aa5c6da052c69bbba9127/README.md?plain=1#L34C1-L43C2

And in the result its called 'SampleUser'
![result](https://github.com/user-attachments/assets/3f6ea5ed-7566-4843-875b-8356a1a01b8e)
https://github.com/invopop/jsonschema/blob/a4467074499db5797e8aa5c6da052c69bbba9127/README.md?plain=1#L58C1-L58C20

**Comment by samlown** [comment]
Nice catch! Thanks!
