### ISSUE TITLE
Maybe add support for a JSONSchema interface to types?

### ISSUE THREAD

**Issue by twpayne** [invopop/jsonschema#17]
This is a fantastic library - thank you!

I'm very new to JSON schemas but am wondering if we can use Go interfaces to give more fine-grained control over JSON schemas to the underlying types represented, similar to how Go's `MarshalJSON` and `UnmarshalJSON` work. This would be an alternative mechanism to the existing `jsonschema.Reflector.Mapper` function.

For example, consider the following type:

```go
package mypackage

type CoinFlip string

const (
    CoinFlipHeads CoinFlip = "heads"
    CoinFlipTails CoinFlip = "tails"
)
```

Let's give it a `JSONSchema` method:

```go
func (CoinFlip) JSONSchema() *jsonschema.Schema {
    return &jsonschema.Schema{
        Type: "string",
        Enum: []interface{}{
            "heads",
            "tails",
        },
    }
}
```

and define an interface in the `jsonschema` package:

```go
package jsonschema

type JSONSchema interface {
    JSONSchema() *jsonschema.Schema
}
```

Now, when generating the JSON schema for a field, we can first check if the field's type implements in the `JSONSchema` interface, and, if so, call its `JSONSchema()` method directly. If the field's type does not implement the `JSONSchema` interface then we can continue with the existing behavior.

Such an approach would effectively allows types to define their own schemas.

Does this make sense? I would be happy to help implement such a feature.

**Comment by JeanChristopheMorinPerso** [comment]
I think it's already implemented, see https://github.com/invopop/jsonschema#custom-type-definitions.

**Comment by twpayne** [comment]
Oops, so sorry for missing that. This is exactly what I was looking for. Thank you and sorry for the noise.
