### ISSUE TITLE
How to add items close to a array in the oneOf schema?

### ISSUE THREAD

**Issue by davidljubadev22** [invopop/jsonschema#26]
This is example of desired schema:
```json
// desired schema ("items": ... are close to "type: "array")
{
    "$schema": "http://json-schema.org/draft/2020-12/schema",
    "$ref": "#/$defs/Foo",
    "$defs": {
        "Foo": {
            "properties": {
                "foos": {
                    "oneOf": [
                        {
                            "items": {
                                "$ref": "#/$defs/Foo"
                            },
                            "type": "array"
                        },
                        {
                            "type": "null"
                        }
                    ]
                }
            },
            "additionalProperties": false,
            "type": "object"
        }
    }
}
```

Bellow is actually a generated schema:

```json
// generated by
// Foos []Foo `json:"foos,omitempty" jsonschema:"oneof_type=array;null,type=array"`
{
    "$schema": "http://json-schema.org/draft/2020-12/schema",
    "$ref": "#/$defs/Foo",
    "$defs": {
        "Foo": {
            "properties": {
                "foos": {
                    "oneOf": [
                        {
                            "type": "array"
                        },
                        {
                            "type": "null"
                        }
                    ],
                    "items": {
                        "$ref": "#/$defs/Foo"
                    },
                    "type": "array"
                }
            },
            "additionalProperties": false,
            "type": "object"
        }
    }
}
```

Is it possible to get desired schema using _invopop/jsonschema_ tags (annotations)?

Thanks

(_This is only question. Feel free to close this issue after answering this question_)

**Comment by samlown** [comment]
Hi! From the outset, no, this isn't possible. I guess in theory it might be possible to match the type defined in the the `oneof_type` box and move the definition over if you'd like to attempt a PR :-)

It's worth stating though that your example doesn't really add any meaning. The base schema doesn't define a list of required properties, so assigning `null` to the array is valid. Go also doesn't really support mapping to different types, so this would be hard to implement and support when parsing JSON. If you really need this, my suggestion would be to define the `JSONSchema` manually. Here's and example to get you started:

```
type Foo struct {
  Foos []*Foo `json:"foo"`
}

func (Foo) JSONSchema() *jsonschema.Schema {
  	return &jsonschema.Schema{
		Type:        "object",
		AdditionalProperties:   false,
		Properties:  []*jsonschema.Schema{
			{
				OneOf: .....
			},
		},
	}
}
```

**Comment by davidljubadev22** [comment]
Unfortunately, there is bug _confluentinc/schema-registry_ project (actually, in depending project).

Above _oneOf_ example is proposed workaround for that bug:   https://github.com/confluentinc/schema-registry/issues/1549#issuecomment-1162191557 .

Will try with use custom schema `JSONSChema()` method.

Tx for your answer!
