### ISSUE TITLE
Postprocessing of schemas based on field information

### ISSUE THREAD

**Issue by arvidfm** [invopop/jsonschema#30]
Is there any way to postprocess the generated schema for a type to add additional information given the corresponding `StructField` object? E.g. to implement custom tags. There's `jsonschema_extras`, but it's relatively limited in that it only really works with string or string array values. `Reflector.Mapper` only passes the `Type`, not the `StructField`, and in any case it's somewhat tricky to use `Mapper` to tell jsonschema to do its own thing and only modify the result (if you just call `ReflectFromType` recursively, the `definitions` map which is passed down the call chain in jsonschema doesn't get populated, which leads to weird behaviour elsewhere, plus you have to be careful so you don't accidentally recurse infinitely).

**Comment by samlown** [comment]
I'm not sure I totally understand your use-case here... you have the `JSONSchema()` custom interface method you use to *replace* a definition.

If you want to post-process a schema that has already been generated, you can just edit the resulting `*jsonschema.Schema` directly.

**Comment by arvidfm** [comment]
Wholly replacing a definition is inconvenient as I don't want to have to reimplement most of jsonschema's behaviour just to change the result slightly. Editing the schema after the fact is not really feasible if I want to post-process every single generated schema, including embedded schemas, as I would have to use reflection to traverse the schema; plus, the field and type information is not available at that point, so I wouldn't be able to implement e.g. custom field tags.

The specific use-case I was looking at was implementing the `example` keyword for types that didn't support it, though in the end I just modified jsonschema itself to implement it, and I have a PR up for it. It would be nice in general though to be able to implement eg custom, application-specific tags that add extra information to the schema. (`jsonschema_extras` is a bit limited.)

**Comment by samlown** [comment]
We now have support for the `JSONSchemaExtend` interface method, which would hopefully solve your problem here.
