### ISSUE TITLE
Duplicated entries in "required" array

### ISSUE THREAD

**Issue by desprit** [invopop/jsonschema#33]
I have a struct that defines base model:

```
type BaseParameters struct {
	Hotel string `json:"hotel" jsonschema:"title=Hotel ID,description=Hotel ID"`
}
```

And a struct that defines client model, which is a subset of base model:

```
type Hotel string

var Hotels []interface{} = []interface{}{"15603"}

type Parameters struct {
	BaseParameters

	Hotel Hotel `json:"hotel"`
}

func (Hotel) JSONSchema() *jsonschema.Schema {
	return &jsonschema.Schema{
		Type: "string",
		Title: "Hotel ID",
		Description: "Hotel ID",
		Enum: Hotels,
	}
}
```

Json schema is:

```
{
  "$schema": "http://json-schema.org/draft/2020-12/schema",
  "$ref": "#/$defs/Parameters",
  "$defs": {
    "Hotel": {
      "type": "string",
      "enum": ["15603"],
      "title": "Hotel ID",
      "description": "Hotel ID"
    },
    "Parameters": {
      "properties": {
        "hotel": {
          "$ref": "#/$defs/Hotel"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "hotel",
        "hotel"
      ]
    }
  }
}
```

Is it by design that `required` contains two entries of `hotel`?

**Comment by samlown** [comment]
Hey! That's a bug, but you're doing strange things overriding the original `hotel` property of type `string` with a new `Hotel` type. I'm not sure I'd recommend doing that with Go as it's really confusing!

If you want a quick fix, maybe you can stick `,omitempty` with the Hotel in the `BaseParameters` struct? We can add a unique check to the list of required properties I guess if you really don't think a refactor is possible.

**Comment by desprit** [comment]
@samlown Thank you for your answer. Yes, in my `BaseParameters` the type should also be `Hotel` and I'm changing it. 
I agree with you about property overriding that it's confusing, I could drop that field from the base struct or, as you mentioned, mark it with `omitempty` but that would prevent me from writing a unit test for a `BaseParameters`. 
Anyways, if property override is something that should be avoided I should better try to fix it on my side then. Didn't have any other way to express the idea that all clients require a "hotel" field while each specific client requires it's own set of hotels.

**Comment by samlown** [comment]
@desprit I've added a quick PR which should fix your issues. Can't help feeling that other related problems might appear with composition and overriding properties, but we'll see.

**Comment by desprit** [comment]
@samlown thank you very much!
