### ISSUE TITLE
Omit empty overrides required

### ISSUE THREAD

**Issue by AdamJSoftware** [invopop/jsonschema#34]
I have noticed that if I put omit empty, it overrides the jsonschema:"required" tag. I feel that this should be the opposite.

Example 

```
type Test struct {
  Name  string  `json:"name,omitempty" jsonschema:"required"`
}
```
This will not be marked as required

**Comment by samlown** [comment]
What's the use-case for wanting to write a contradictory tag? I can kind of understand omitting `,omitempty` and then adding `required` to the json schema, but directly contradicting oneself feels strange... would be great to understand more!
