### ISSUE TITLE
[bug]default value of number will get int

### ISSUE THREAD

**Issue by hsz1273327** [invopop/jsonschema#38]
so if using the default value,it can not set into the struct .
![截屏2022-07-25 下午4 11 22](https://user-images.githubusercontent.com/7850148/180731018-65f776aa-c662-4221-874a-23e33411dc5f.png)
![截屏2022-07-25 下午4 11 42](https://user-images.githubusercontent.com/7850148/180731027-21aeb295-36c1-4a8a-8bc2-bad068062235.png)

**Comment by samlown** [comment]
Hi! Not sure I understand your problem here. Could you give an example of what is not working as expected? Thanks.

**Comment by hsz1273327** [comment]
for example:
```go
package main

import (
	"encoding/json"
	"fmt"

	"github.com/invopop/jsonschema"
)

type SampleUser struct {
	FloatExp float64 `json:"floatexp" jsonschema:"default=12.3"`
}

func main() {
	s := jsonschema.Reflect(&SampleUser{})
	data, err := json.MarshalIndent(s, "", "  ")
	if err != nil {
		panic(err.Error())
	}
	fmt.Println(string(data))
}

```
will get:

```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$ref": "#/$defs/SampleUser",
  "$defs": {
    "SampleUser": {
      "properties": {
        "floatexp": {
          "type": "number",
          "default": 0
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "floatexp"
      ]
    }
  }
}
```

**Comment by HarunOr** [comment]
> Hi! Not sure I understand your problem here. Could you give an example of what is not working as expected? Thanks.

The default values set in struct tags get overwritten and are always 0 for float types.
This [PR](https://github.com/invopop/jsonschema/pull/31) seems to fix it though.

**Comment by hsz1273327** [comment]
send a pull request #55  to fix
