### ISSUE TITLE
Is `anyof_required` supported?

### ISSUE THREAD

**Issue by deepjyoti30** [invopop/jsonschema#41]
I saw from the examples in README that `oneof_required` is supported however there was no mention of `anyOf`. Looked through the source code and found that there's just one place in the code where `anyOf` is defined but for `oneof_required` there were a few lines that was parsing the `oneof_required` into the parent. [Code for that can be found here](https://github.com/invopop/jsonschema/blob/4a807f958afcd754864be5c16b0d53ca6cef53d5/reflect.go#L671)

My question is whether or not `anyof_required` is supported in the same way that `oneof_required` is supported. I tried generating the schema with `anyof_required` and it didn't generate any `anyOf` array however `anyOf` is a valid part of JSON schema so it should be supported?

**Comment by samlown** [comment]
Hi! No, not at the moment, but as you say, the implementation would be quite similar to the `oneof` syntax. PRs welcome :-)

My recommendations for these rare cases would be to avoid the Go tags and define your own `JSONSchema` method. You can find an example of defining the `oneOf` property manually here: https://github.com/invopop/gobl/blob/main/org/notes.go#L263-L278 The implementation with `anyOf` would be very similar.

**Comment by deepjyoti30** [comment]
Hey @samlown added a PR for supporting `anyof_required` and `anyof_type`. Will close this issue once the PR is merged.

**Comment by samlown** [comment]
This should be sorted now. Closing.
