### ISSUE TITLE
Custom schema attribute which is a JSON array.

### ISSUE THREAD

**Issue by tpoxa** [invopop/jsonschema#54]
I use `jsonschema_extras` to add my own schema attributes. But unfortunately, it does not work with JSON array values (don't confuse them with multiple values)

An example:
```
Some interface{} `json:"some,omitempty" jsonschema_extras:"requiredWhen=[1,2,3]"`
```

Returns me

```
..."some":{"requiredWhen":"[1"}},"additionalProperties":false....
```

I guess the problem is with a comma separator.  
Should I try implementing `JSONSchema`? Would it be possible with it?

Many thanks in advance!

**Comment by webdestroya** [comment]
You should define it like:

```
Some interface{} `json:"some,omitempty"  jsonschema_extras:"requiredWhen=1,requiredWhen=2,requiredWhen=3"`
```

**Comment by tpoxa** [comment]
Thanks @webdestroya!
