### ISSUE TITLE
Field should only be marked required if set in JSON Schema

### ISSUE THREAD

**Issue by djarbz** [invopop/jsonschema#59]
I've been trying to figure out why all of my struct fields are being marked as required until I found [this](https://github.com/invopop/jsonschema/blob/9f28aff52929bf3e7080ad118eb3c9f0c5e01f5c/reflect.go#L1004-L1007) in your code.

In effect, if I don't specify the JSON omitempty tag, it will mark all struct fields as required.

IMHO, the required condition should be set via your tags and not by omitempty. The omitempty tag prevents the JSON from outputting that field if it is not defined, but that doesn't necessarily mean that it is required or not. This also means that we need to mark every struct field as either omitempty or required.

**Comment by james-d-elliott** [comment]
https://github.com/invopop/jsonschema/blob/main/reflect.go#L172-L175

**Comment by djarbz** [comment]
Awesome, thank you.

**Comment by james-d-elliott** [comment]
No worries, was looking for the same thing, then found it. Sharing the knowledge. :)
