### ISSUE TITLE
Feature request: support oneof_ref

### ISSUE THREAD

**Issue by gmlewis** [invopop/jsonschema#68]
It would be nice to use `oneof_ref` such that a field could be one of several already-defined objects, as suggested here:
https://stackoverflow.com/questions/57414600/json-schema-oneof-with-ref-to-wildcard-path

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$defs": {
    "ipv4": {...},
    "ipv6": {...}
    "ipAddress": {
      "oneOf": [{
          "$ref": "#/$defs/ipv4"
      },{
          "$ref": "#/$defs/ipv6"
      }]
    }
  }
  "properties": {
    "anIPAddress": {
      "$ref": "#/$defs/ipAddress"
    }
  }
}
```

and the Go code would look something like:

```go
...
	IPAddress    any    `json:"ipAddress" jsonschema:"oneof_ref=#/$defs/ipv4;#/$defs/ipv6"`
...
```

I'll try to put together a PR.

**Comment by rclsilver** [comment]
Hi, any chance to get this PR merged soon?
