### ISSUE TITLE
How to build API?

### ISSUE THREAD

**Issue by ivanjaros** [invopop/jsonschema#74]
How should I build API schema when I have http methods, paths and json schema for requests and responses?

Right now I am thinking about `map[HTTP_METHOD:HTTP_PATH]{Request: {}, Response{}}` but it does not feel right.

Also, is there a way to generate openapi from this, or some kind of web-ish documentation for technically less literate folk?

**Comment by samlown** [comment]
Hi @ivanjaros! Sounds like you want to be using something like https://github.com/swaggest/openapi-go instead!
