### ISSUE TITLE
Add option for "pattern" of array items

### ISSUE THREAD

**Issue by amiramw** [invopop/jsonschema#78]
similar to https://github.com/invopop/jsonschema/issues/24

Example:

```
type Repo struct {
	Foos   []string `yaml:"foos"   json:"URLs"    jsonschema:"type=array,pattern=^.*[^*]$"`
}
```

**Comment by funte** [comment]
Just add two lines in `Schema.arrayKeywords` function:
```go
case "pattern":
  t.Items.Pattern = val
```
I has fork this project and add some new features at https://github.com/funte/jsonschema
